{
  "formatVersion": "1.1",
  "component": {
    "group": "com.galaxybruce.android",
    "module": "pioneer-gradle-plugin",
    "version": "0.0.54",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pioneer-gradle-plugin-0.0.54.jar",
          "url": "pioneer-gradle-plugin-0.0.54.jar",
          "size": 193231,
          "sha512": "b11c79a75ef0bce4c390daace023232ce892c94a1a8ea57fcf40464564061cf5303476cb01fe09aca63c4c61cf1aafc21eda86e857580c88a901aa606982b659",
          "sha256": "08b4551bee08c755b3d50d570fd63612546f42beece971ca68a226bdc0a2857f",
          "sha1": "b90e8134a4e6dd354cd8cbe5ee328eeeab61cb31",
          "md5": "488eaa7bf0b8779b44c02c43d5ead926"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.0.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.51"
          }
        }
      ],
      "files": [
        {
          "name": "pioneer-gradle-plugin-0.0.54.jar",
          "url": "pioneer-gradle-plugin-0.0.54.jar",
          "size": 193231,
          "sha512": "b11c79a75ef0bce4c390daace023232ce892c94a1a8ea57fcf40464564061cf5303476cb01fe09aca63c4c61cf1aafc21eda86e857580c88a901aa606982b659",
          "sha256": "08b4551bee08c755b3d50d570fd63612546f42beece971ca68a226bdc0a2857f",
          "sha1": "b90e8134a4e6dd354cd8cbe5ee328eeeab61cb31",
          "md5": "488eaa7bf0b8779b44c02c43d5ead926"
        }
      ]
    }
  ]
}
