{
  "formatVersion": "1.1",
  "component": {
    "group": "com.galaxybruce.android",
    "module": "pioneer-gradle-plugin",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pioneer-gradle-plugin-0.1.0-SNAPSHOT.jar",
          "url": "pioneer-gradle-plugin-0.1.0-SNAPSHOT.jar",
          "size": 193265,
          "sha512": "12760ef753f32ef26e6be14899c7216c224143fc94a8187fe1bb50372fb7e844d9770f12ac05c376e13d719b2331c6919e85a0ed462d0afaae5132f560fa01fa",
          "sha256": "1edad1c877695c76fd3cbfef0fc824525d6a9533f8ce942bf5fbbb65e9a1ee12",
          "sha1": "18d91b9add9eb5c86145a80fb9a58e917c405892",
          "md5": "c55e14a3fd4d8849725ac2b97a471c26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.0.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.51"
          }
        }
      ],
      "files": [
        {
          "name": "pioneer-gradle-plugin-0.1.0-SNAPSHOT.jar",
          "url": "pioneer-gradle-plugin-0.1.0-SNAPSHOT.jar",
          "size": 193265,
          "sha512": "12760ef753f32ef26e6be14899c7216c224143fc94a8187fe1bb50372fb7e844d9770f12ac05c376e13d719b2331c6919e85a0ed462d0afaae5132f560fa01fa",
          "sha256": "1edad1c877695c76fd3cbfef0fc824525d6a9533f8ce942bf5fbbb65e9a1ee12",
          "sha1": "18d91b9add9eb5c86145a80fb9a58e917c405892",
          "md5": "c55e14a3fd4d8849725ac2b97a471c26"
        }
      ]
    }
  ]
}
