{
  "formatVersion": "1.1",
  "component": {
    "group": "com.galaxybruce.android",
    "module": "pioneer-gradle-plugin",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pioneer-gradle-plugin-0.1.5.jar",
          "url": "pioneer-gradle-plugin-0.1.5.jar",
          "size": 207392,
          "sha512": "125e78985c426c6497558d7b819d59e6f7a06360b8f76f6125ed94aff8b62cf8716843e633314400a4889c5cad5c085e62f707790459b89194128fe01196ef1e",
          "sha256": "28ff545d1bd159958e836e350d15865add135cbda4c1cb3cae2cf360dfd1feac",
          "sha1": "09ab91db87794c2d886678f4f14b387d66c32479",
          "md5": "5f8dc0aee2bc8f33246afcea85d379e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.0.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.51"
          }
        }
      ],
      "files": [
        {
          "name": "pioneer-gradle-plugin-0.1.5.jar",
          "url": "pioneer-gradle-plugin-0.1.5.jar",
          "size": 207392,
          "sha512": "125e78985c426c6497558d7b819d59e6f7a06360b8f76f6125ed94aff8b62cf8716843e633314400a4889c5cad5c085e62f707790459b89194128fe01196ef1e",
          "sha256": "28ff545d1bd159958e836e350d15865add135cbda4c1cb3cae2cf360dfd1feac",
          "sha1": "09ab91db87794c2d886678f4f14b387d66c32479",
          "md5": "5f8dc0aee2bc8f33246afcea85d379e6"
        }
      ]
    }
  ]
}
