{
  "formatVersion": "1.1",
  "component": {
    "group": "com.galaxybruce.android",
    "module": "pioneer-gradle-plugin",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pioneer-gradle-plugin-0.1.5.jar",
          "url": "pioneer-gradle-plugin-0.1.5.jar",
          "size": 206867,
          "sha512": "97d7c9f6a75379b4e95ac48fdb06939764b9b3b1c32d694ce30e5d0d99e8e9c9c7744364487bd6a403ed62b009d45b2a0d6ca360f7415a01420baae168c54a81",
          "sha256": "17cc15b871b94e790be183c86e82ac17072ad59387ffd2795645c70c4eea1f1e",
          "sha1": "193c329f21a99eb6c238486b3f9221c1ecd20c28",
          "md5": "b1a96ec16a59ba4ca3bdcf221ff7a3fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.0.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.51"
          }
        }
      ],
      "files": [
        {
          "name": "pioneer-gradle-plugin-0.1.5.jar",
          "url": "pioneer-gradle-plugin-0.1.5.jar",
          "size": 206867,
          "sha512": "97d7c9f6a75379b4e95ac48fdb06939764b9b3b1c32d694ce30e5d0d99e8e9c9c7744364487bd6a403ed62b009d45b2a0d6ca360f7415a01420baae168c54a81",
          "sha256": "17cc15b871b94e790be183c86e82ac17072ad59387ffd2795645c70c4eea1f1e",
          "sha1": "193c329f21a99eb6c238486b3f9221c1ecd20c28",
          "md5": "b1a96ec16a59ba4ca3bdcf221ff7a3fd"
        }
      ]
    }
  ]
}
