{
  "formatVersion": "1.1",
  "component": {
    "group": "com.galaxybruce.android",
    "module": "pioneer-gradle-plugin",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pioneer-gradle-plugin-0.1.5.jar",
          "url": "pioneer-gradle-plugin-0.1.5.jar",
          "size": 205825,
          "sha512": "c5aeb03f9c6c99993772613edf932468e4c6399a6ff96053ab94735bad44a6d0fb45073ce4754797788bdc2189660ea3d16e2cf360fc1f6f809a48eb6268ea20",
          "sha256": "5a388d3401177f56e871a7b33d86d57889fa50a1d03a4402cba1c13399e44759",
          "sha1": "452ef6da51ae2f44016f786b6cb24a58ac2b2336",
          "md5": "a8801589b883f761b0eeec10fa6f41ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.0.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.51"
          }
        }
      ],
      "files": [
        {
          "name": "pioneer-gradle-plugin-0.1.5.jar",
          "url": "pioneer-gradle-plugin-0.1.5.jar",
          "size": 205825,
          "sha512": "c5aeb03f9c6c99993772613edf932468e4c6399a6ff96053ab94735bad44a6d0fb45073ce4754797788bdc2189660ea3d16e2cf360fc1f6f809a48eb6268ea20",
          "sha256": "5a388d3401177f56e871a7b33d86d57889fa50a1d03a4402cba1c13399e44759",
          "sha1": "452ef6da51ae2f44016f786b6cb24a58ac2b2336",
          "md5": "a8801589b883f761b0eeec10fa6f41ae"
        }
      ]
    }
  ]
}
