{
  "formatVersion": "1.1",
  "component": {
    "group": "com.galaxybruce.android",
    "module": "pioneer-gradle-plugin",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pioneer-gradle-plugin-0.1.0.jar",
          "url": "pioneer-gradle-plugin-0.1.0.jar",
          "size": 193045,
          "sha512": "f6d787d8f7196b537b76128a9605d4799f0613512b2e85e2e8b7cf58d4a21fb078ad93e41ac7b09028c938b408ccf580703653ab576a8c949efd583105665348",
          "sha256": "bdfc3ae5a9eff04cc0a5ff4f507a601cce2266e015248253b75fdef1e3fefa7a",
          "sha1": "3685cfb31c25be6933d1dbc0f8cdb6c984f37390",
          "md5": "7c799fd026bec083f6b1c676631f8a0f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.0.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.51"
          }
        }
      ],
      "files": [
        {
          "name": "pioneer-gradle-plugin-0.1.0.jar",
          "url": "pioneer-gradle-plugin-0.1.0.jar",
          "size": 193045,
          "sha512": "f6d787d8f7196b537b76128a9605d4799f0613512b2e85e2e8b7cf58d4a21fb078ad93e41ac7b09028c938b408ccf580703653ab576a8c949efd583105665348",
          "sha256": "bdfc3ae5a9eff04cc0a5ff4f507a601cce2266e015248253b75fdef1e3fefa7a",
          "sha1": "3685cfb31c25be6933d1dbc0f8cdb6c984f37390",
          "md5": "7c799fd026bec083f6b1c676631f8a0f"
        }
      ]
    }
  ]
}
