{
  "formatVersion": "1.1",
  "component": {
    "group": "com.galaxybruce",
    "module": "testlibrary-app2",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "testlibrary-app2-1.0.1-SNAPSHOT.aar",
          "url": "testlibrary-app2-1.0.1-SNAPSHOT.aar",
          "size": 20037,
          "sha512": "25f4c3fd49a9c0243ec5ef353a991d7fd28b62748d688fa8dba77100c1700c1e5cf28ab88df4465ab18385eb457cb924e403952fc054758dd7368b48f764fa5c",
          "sha256": "ca67a423635e5e48ebc26937362e715043cbc000bb356bf214bec8e5c56bc541",
          "sha1": "8562ea2fae1870bf5c198199eda08b6ab4662806",
          "md5": "b65256f6d8c95a9dbdf644b6cf51d2e1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.33"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "testlibrary-app2-1.0.1-SNAPSHOT.aar",
          "url": "testlibrary-app2-1.0.1-SNAPSHOT.aar",
          "size": 20037,
          "sha512": "25f4c3fd49a9c0243ec5ef353a991d7fd28b62748d688fa8dba77100c1700c1e5cf28ab88df4465ab18385eb457cb924e403952fc054758dd7368b48f764fa5c",
          "sha256": "ca67a423635e5e48ebc26937362e715043cbc000bb356bf214bec8e5c56bc541",
          "sha1": "8562ea2fae1870bf5c198199eda08b6ab4662806",
          "md5": "b65256f6d8c95a9dbdf644b6cf51d2e1"
        }
      ]
    }
  ]
}
