{
  "formatVersion": "1.1",
  "component": {
    "group": "com.galaxybruce.android",
    "module": "pioneer-gradle-plugin",
    "version": "0.0.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pioneer-gradle-plugin-0.0.51.jar",
          "url": "pioneer-gradle-plugin-0.0.51.jar",
          "size": 198446,
          "sha512": "aa311d826477487dd41e0d3e0ae63c1a7d128fe57d58afab4ea11a0056918230223c7c2b9aa09dcb095cf516838106a7b6c3dc05dadf281c5969cc12c44416e1",
          "sha256": "f0df17e5df498af69b27ba5297029d2befd3d66c761e499ea4dfe6ffd5ac5c4d",
          "sha1": "9e120391162f63c850f9e62c06bcbeac18e45d61",
          "md5": "ebd6f610077dd7c04f4fa4400333bf53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.0.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.51"
          }
        }
      ],
      "files": [
        {
          "name": "pioneer-gradle-plugin-0.0.51.jar",
          "url": "pioneer-gradle-plugin-0.0.51.jar",
          "size": 198446,
          "sha512": "aa311d826477487dd41e0d3e0ae63c1a7d128fe57d58afab4ea11a0056918230223c7c2b9aa09dcb095cf516838106a7b6c3dc05dadf281c5969cc12c44416e1",
          "sha256": "f0df17e5df498af69b27ba5297029d2befd3d66c761e499ea4dfe6ffd5ac5c4d",
          "sha1": "9e120391162f63c850f9e62c06bcbeac18e45d61",
          "md5": "ebd6f610077dd7c04f4fa4400333bf53"
        }
      ]
    }
  ]
}
