{
  "formatVersion": "1.1",
  "component": {
    "group": "com.galaxybruce.android",
    "module": "pioneer-gradle-plugin",
    "version": "1.0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pioneer-gradle-plugin-1.0.1.2.jar",
          "url": "pioneer-gradle-plugin-1.0.1.2.jar",
          "size": 202211,
          "sha512": "e3620ccc3e52c7471e5371151bc4ea5ed93f8a303553aa4833e4188afaffc1195b6eff928ebd70b00e6f2750080cdd1aeb3b5dce3bf5fabe090442f5e5a00bfb",
          "sha256": "1cb639b5c104f9ee9d6bffab03b17ae4ad59541f36259a41a0118b4d2244e4e9",
          "sha1": "b85f0ac500490c126afb0ed27b10334875f2dac9",
          "md5": "3fc140c6d74fb6c05787e3234f9bd1d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.0.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.51"
          }
        }
      ],
      "files": [
        {
          "name": "pioneer-gradle-plugin-1.0.1.2.jar",
          "url": "pioneer-gradle-plugin-1.0.1.2.jar",
          "size": 202211,
          "sha512": "e3620ccc3e52c7471e5371151bc4ea5ed93f8a303553aa4833e4188afaffc1195b6eff928ebd70b00e6f2750080cdd1aeb3b5dce3bf5fabe090442f5e5a00bfb",
          "sha256": "1cb639b5c104f9ee9d6bffab03b17ae4ad59541f36259a41a0118b4d2244e4e9",
          "sha1": "b85f0ac500490c126afb0ed27b10334875f2dac9",
          "md5": "3fc140c6d74fb6c05787e3234f9bd1d7"
        }
      ]
    }
  ]
}
